#!/bin/bash

BACKEND_IMAGE_NAME="jobhub-backend"
FRONTEND_IMAGE_NAME="jobhub-frontend"
DOCKERHUB_USERNAME="maaarsss"
TAG="latest"

BACKEND_IMAGE="$DOCKERHUB_USERNAME/$BACKEND_IMAGE_NAME:$TAG"
FRONTEND_IMAGE="$DOCKERHUB_USERNAME/$FRONTEND_IMAGE_NAME:$TAG"

docker tag $BACKEND_IMAGE_NAME $BACKEND_IMAGE
docker tag $FRONTEND_IMAGE_NAME $FRONTEND_IMAGE

docker push $BACKEND_IMAGE
docker push $FRONTEND_IMAGE